import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./main.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "House Plant Shop | Nationwide Free Shipping on all indoor Plants",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.ico",
      type: "image/png",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.ico" />
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
