import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./GolbalRedux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ACEFIC 5",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ margin: 0, overflowX: "hidden" }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
